export const DEMO_SUMMARY = {
  metrics: {
    aamcCoveragePercent: 87,
    usmleGaps: 3,
    avgConfidence: 0.82,
    guidesProcessed: 4,
    usmleDomainsCovered: 14,
    usmleDomainsTotal: 18,
  },
  aamcDomainCoverage: [
    { domain: "Patient Care", percent: 92 },
    { domain: "Medical Knowledge", percent: 88 },
    { domain: "Interpersonal Communication", percent: 85 },
    { domain: "Professionalism", percent: 90 },
    { domain: "Practice-Based Learning", percent: 78 },
    { domain: "Systems-Based Practice", percent: 80 },
  ],
  gaps: [
    {
      frameworkLabel: "USMLE: Renal/Urinary",
      coverageStatus: "gap",
      frameworkId: "Renal/Urinary",
    },
    {
      frameworkLabel: "USMLE: Cardiovascular",
      coverageStatus: "partial",
      frameworkId: "Cardiovascular",
    },
    {
      frameworkLabel: "USMLE: Dermatology",
      coverageStatus: "gap",
      frameworkId: "Musculoskeletal/Dermatology",
    },
  ],
};

export const DEMO_CASES = [
  { id: 1, caseNumber: 1, caseTitle: "David Tilo", diagnosis: "GERD with gastric ulcer" },
  { id: 2, caseNumber: 2, caseTitle: "Jessica Donner", diagnosis: "Pediatric GI/nutrition" },
  { id: 3, caseNumber: 3, caseTitle: "Marie Hernandez", diagnosis: "Bacterial meningitis" },
  { id: 4, caseNumber: 4, caseTitle: "John Jackson", diagnosis: "Alcohol-related cirrhosis" },
];

export const DEMO_OBJECTIVES = {
  total: 6,
  regexCount: 5,
  llmCount: 1,
  byCase: [
    { caseNumber: 1, caseTitle: "David Tilo", count: 2 },
    { caseNumber: 2, caseTitle: "Jessica Donner", count: 2 },
    { caseNumber: 4, caseTitle: "John Jackson", count: 2 },
  ],
  objectives: [
    {
      id: 1,
      ordinal: 1,
      text: "Identify the abdominal viscera of the foregut (i.e., stomach, duodenum, liver, pancreas, gallbladder, and spleen), describe their internal and external features, describe their relationships to adjacent structures, explain their major functional roles, and name their arterial supply and venous drainage. (EO-0052)",
      sectionHeading: "Case Specific Objectives",
      eoCode: "EO-0052",
      extractionMethod: "regex",
      confidence: "high",
      caseNumber: 1,
      caseTitle: "David Tilo",
      filename: "RMD563_FacultyGuide_Case1_DavidTilo.pdf",
    },
    {
      id: 2,
      ordinal: 2,
      text: "Identify and demonstrate all of the branches of the celiac trunk and list the organs they supply. (EO-0053)",
      sectionHeading: "Case Specific Objectives",
      eoCode: "EO-0053",
      extractionMethod: "regex",
      confidence: "high",
      caseNumber: 1,
      caseTitle: "David Tilo",
      filename: "RMD563_FacultyGuide_Case1_DavidTilo.pdf",
    },
    {
      id: 3,
      ordinal: 1,
      text: "Describe the epidemiology and main characteristics of common pediatric GI conditions.",
      sectionHeading: "Learning Objectives",
      eoCode: null,
      extractionMethod: "regex",
      confidence: "high",
      caseNumber: 2,
      caseTitle: "Jessica Donner",
      filename: "RMD563_FacultyGuide_Case2_JessicaDonner.docx",
    },
    {
      id: 4,
      ordinal: 2,
      text: "Explain nutritional assessment strategies for pediatric patients.",
      sectionHeading: "Learning Objectives",
      eoCode: null,
      extractionMethod: "llm_cleanup",
      confidence: "high",
      caseNumber: 2,
      caseTitle: "Jessica Donner",
      filename: "RMD563_FacultyGuide_Case2_JessicaDonner.docx",
    },
    {
      id: 5,
      ordinal: 1,
      text: "Discuss the epidemiology and main characteristics of HAV, HBV, HCV, HDV and HEV hepatitis and how they may be prevented.",
      sectionHeading: "Learning Objectives",
      eoCode: null,
      extractionMethod: "regex",
      confidence: "high",
      caseNumber: 4,
      caseTitle: "John Jackson",
      filename: "RMD563_FacultyGuide_Case4_JohnJackson.docx",
    },
    {
      id: 6,
      ordinal: 2,
      text: "Define \"serologic window\" in HBV infection.",
      sectionHeading: "Learning Objectives",
      eoCode: null,
      extractionMethod: "regex",
      confidence: "high",
      caseNumber: 4,
      caseTitle: "John Jackson",
      filename: "RMD563_FacultyGuide_Case4_JohnJackson.docx",
    },
  ],
};
